Made launcher script more resilient

diff --git a/launcher b/launcher
--- a/launcher
+++ b/launcher
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-declare portFile startupFile ttystate
-declare -i pid port catPid continue
+declare portFile startupFile ttystate script
+declare -i pid port streamPid continue pipePid
 declare -a args signals
 
 continue=1
@@ -9,6 +9,7 @@ continue=1
 # The name of the file which will contain the port number
 portFile="$XDG_RUNTIME_DIR/fury.port"
 startupFile="$XDG_RUNTIME_DIR/fury.start"
+script="$0"
 
 # The set of signals which should be captured and forwarded to the JVM process
 signals=(INT WINCH TERM)
@@ -22,7 +23,7 @@ fi
 
 launch() {
   mkfifo "$startupFile" 2>/dev/null && nohup wrath -x > /home/propensive/work/exoskeleton/out.log 2>&1 &
-  timeout 10 cat "$startupFile"
+  timeout 10 cat "$startupFile" # || terminate "Failed to start server"
   daemon
 }
 
@@ -34,11 +35,17 @@ daemon() {
   port=$(cat "$portFile")
 }
 
+terminate() {
+  continue=0
+  printf '\n%s\n' "$1"
+  kill -TERM -$pid
+}
+
 signal() {
   if [ "$1" = "TERM" ]
   then continue=0
   fi
-  printf "signal %s\nprocess %s\n" "$1" "$pid" | nc -q 1 localhost $port
+  printf "signal %s\nprocess %s\n" "$1" "$pid" | nc -q 1 localhost $port || terminate "Lost server connection"
 }
 
 registerTraps() {
@@ -47,8 +54,9 @@ registerTraps() {
   done
 }
 
-init() {
+stream() {
   printf "process %s\n" "$pid"
+  printf "script %s\n" "$script"
 
   for arg in "${args[@]}"
   do printf "arg %s\n" "$arg"
@@ -67,26 +75,32 @@ init() {
   exec cat
 }
 
+pipe() {
+  local tmpPipe
+  tmpPipe="$(mktemp -u)"
+  mkfifo -m 600 "$tmpPipe"
+  exec 3<> "$tmpPipe"
+  rm "$tmpPipe"
+  stream <&0 >&3 &
+  streamPid=$!
+  nc -q 1 localhost $port <&3 &
+  pipePid=$!
+}
+
 if [ -t 0 ]
 then stty intr undef -echo -icanon min 1 raw time 0 >/dev/null 2>&1
 fi
 
-daemon
-
-tmppipe="$(mktemp -u)"
-mkfifo -m 600 "$tmppipe"
-exec 3<> "$tmppipe"
-rm "$tmppipe"
-init <&0 >&3 &
-catPid=$!
-nc localhost $port <&3 &
-
+daemon && pipe
 registerTraps
 
 while [ $continue = 1 ]
-do wait
+do
+  wait $pipePid
+  if ! ps $pipePid >/dev/null
+  then continue=0
+  fi
 done
 
-kill $catPid
-
+kill $streamPid
 stty "$ttystate"
