Update reversioning script

diff --git a/etc/reversion b/etc/reversion
--- a/etc/reversion
+++ b/etc/reversion
@@ -1,12 +1,57 @@
 #!/bin/sh
 NEWVERSION="$1"
+
+FAIL="0"
+
+for MOD in mod/*
+do
+  cd $MOD
+  if [ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]
+  then
+    echo "$MOD is not on the main branch"
+    exit 1
+  fi
+  git diff-index --quiet HEAD -- || echo "$MOD has uncommitted changes"
+  git diff-index --quiet HEAD -- || FAIL="1"
+  cd ../..
+done
+
+if [ "$FAIL" == "1" ]
+then
+  echo "Aborting"
+  exit 1
+fi
+
+echo done
+exit 1
 if [ -z "$NEWVERSION" ]
 then
   echo "Please specify the new version number as the first parameter"
   exit 1
 fi
-for x in mod/*
+for MOD in mod/*
 do
-  jq --arg ver "$1" '.modules[].version |= $ver' $x/build.vex > $x/.build.vex.tmp && mv $x/.build.vex.tmp $x/build.vex
+  jq --arg ver "$1" '.modules[].version |= $ver' $MOD/build.vex > $MOD/.build.vex.tmp && mv $MOD/.build.vex.tmp $MOD/build.vex
 done
 
+etc/headers
+
+for MOD in mod/*
+do
+  cd $MOD
+  git add build.vex src
+  git commit -m "Update version to $NEWVERSION"
+  git push
+  echo "Tagging v$NEWVERSION"
+  git tag "v$NEWVERSION"
+  git push --tags
+  cd ../..
+done
+
+git add mod/*
+git commit -m "Update version to $NEWVERSION"
+git push
+echo "Tagging v$NEWVERSION"
+git tag "v$NEWVERSION"
+git push --tags
+echo Done
